// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.1
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "ui.h"
#include "ui_helpers.h"

///////////////////// VARIABLES ////////////////////

// SCREEN: ui_Screen1
void ui_Screen1_screen_init(void);
lv_obj_t *ui_Screen1;
lv_obj_t *ui_Image_bg;
lv_obj_t *ui_Slider_AC;
lv_obj_t *ui_Label_AC;
lv_obj_t *ui_Label_Temp;
lv_obj_t *ui_Image1;
lv_obj_t *ui_Label_Date;
lv_obj_t *ui_Label_Time;
lv_obj_t *ui_Slider_Lamp;
lv_obj_t *ui_Label_Lux;
lv_obj_t *ui_Label_Lamp;
lv_obj_t *ui_Image2;
lv_obj_t *ui_Image_Lamp;
lv_obj_t *ui_Image_Lux;
lv_obj_t *ui_Container_TV;
lv_obj_t *ui_Image_TV;
lv_obj_t *ui_Image_TV_Off;
lv_obj_t *ui_Container_AC;
lv_obj_t *ui_Image_AC;
lv_obj_t *ui_Image_AC_On;
lv_obj_t *ui_Slider_Vacuum;
lv_obj_t *ui_Label_VC;
lv_obj_t *ui_Label_VCB;
lv_obj_t *ui_Image3;
lv_obj_t *ui_Image_Vacuum;
lv_obj_t *ui_Image_Vacuumoff;
lv_obj_t *ui_Button_AC;
lv_obj_t *ui_Button_Lamp;
lv_obj_t *ui_Button_TV;
lv_obj_t *ui_Button_VC;
// CUSTOM VARIABLES

// EVENTS
lv_obj_t *ui____initial_actions0;

// IMAGES AND IMAGE SETS

///////////////////// TEST LVGL SETTINGS ////////////////////
#if LV_COLOR_DEPTH != 16
    #error "LV_COLOR_DEPTH should be 16bit to match SquareLine Studio's settings"
#endif
#if LV_COLOR_16_SWAP !=1
    #error "LV_COLOR_16_SWAP should be 1 to match SquareLine Studio's settings"
#endif

///////////////////// ANIMATIONS ////////////////////

///////////////////// FUNCTIONS ////////////////////

///////////////////// SCREENS ////////////////////

void ui_init( void )
{
lv_disp_t *dispp = lv_disp_get_default();
lv_theme_t *theme = lv_theme_default_init(dispp, lv_palette_main(LV_PALETTE_BLUE), lv_palette_main(LV_PALETTE_RED), true, LV_FONT_DEFAULT);
lv_disp_set_theme(dispp, theme);
ui_Screen1_screen_init();
ui____initial_actions0 = lv_obj_create(NULL);
lv_disp_load_scr( ui_Screen1);
}
