// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.1
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#ifndef _SQUARELINE_PROJECT_UI_H
#define _SQUARELINE_PROJECT_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#if defined __has_include
  #if __has_include("lvgl.h")
    #include "lvgl.h"
  #elif __has_include("lvgl/lvgl.h")
    #include "lvgl/lvgl.h"
  #else
    #include "lvgl.h"
  #endif
#else
  #include "lvgl.h"
#endif

#include "ui_helpers.h"
#include "ui_events.h"

// SCREEN: ui_Screen1
void ui_Screen1_screen_init(void);
extern lv_obj_t *ui_Screen1;
extern lv_obj_t *ui_Image_bg;
extern lv_obj_t *ui_Slider_AC;
extern lv_obj_t *ui_Label_AC;
extern lv_obj_t *ui_Label_Temp;
extern lv_obj_t *ui_Image1;
extern lv_obj_t *ui_Label_Date;
extern lv_obj_t *ui_Label_Time;
extern lv_obj_t *ui_Slider_Lamp;
extern lv_obj_t *ui_Label_Lux;
extern lv_obj_t *ui_Label_Lamp;
extern lv_obj_t *ui_Image2;
extern lv_obj_t *ui_Image_Lamp;
extern lv_obj_t *ui_Image_Lux;
extern lv_obj_t *ui_Container_TV;
extern lv_obj_t *ui_Image_TV;
extern lv_obj_t *ui_Image_TV_Off;
extern lv_obj_t *ui_Container_AC;
extern lv_obj_t *ui_Image_AC;
extern lv_obj_t *ui_Image_AC_On;
extern lv_obj_t *ui_Slider_Vacuum;
extern lv_obj_t *ui_Label_VC;
extern lv_obj_t *ui_Label_VCB;
extern lv_obj_t *ui_Image3;
extern lv_obj_t *ui_Image_Vacuum;
extern lv_obj_t *ui_Image_Vacuumoff;
extern lv_obj_t *ui_Button_AC;
extern lv_obj_t *ui_Button_Lamp;
extern lv_obj_t *ui_Button_TV;
extern lv_obj_t *ui_Button_VC;
// CUSTOM VARIABLES

// EVENTS
extern lv_obj_t *ui____initial_actions0;

// IMAGES AND IMAGE SETS
LV_IMG_DECLARE( ui_img_1015890679);   // assets/Images/bg-1.png
LV_IMG_DECLARE( ui_img_1565510499);   // assets/Images/circle-heat-svgrepo-com 1.png
LV_IMG_DECLARE( ui_img_1819326991);   // assets/Images/lightbulb-alt-svgrepo-com 1.png
LV_IMG_DECLARE( ui_img_images_lamp_png);   // assets/Images/lamp.png
LV_IMG_DECLARE( ui_img_images_lux_png);   // assets/Images/lux.png
LV_IMG_DECLARE( ui_img_403521860);   // assets/Images/tv-on.png
LV_IMG_DECLARE( ui_img_310970492);   // assets/Images/tv-off.png
LV_IMG_DECLARE( ui_img_images_ac_png);   // assets/Images/ac.png
LV_IMG_DECLARE( ui_img_330396823);   // assets/Images/ac-on 1.png
LV_IMG_DECLARE( ui_img_1844661879);   // assets/Images/battery-empty-svgrepo-com 1.png
LV_IMG_DECLARE( ui_img_images_vacuum_cleaner_png);   // assets/Images/Vacuum Cleaner.png
LV_IMG_DECLARE( ui_img_580765743);   // assets/Images/Vacuum Cleaner-off.png

// FONTS
LV_FONT_DECLARE( ui_font_KR20);
LV_FONT_DECLARE( ui_font_KR25);
LV_FONT_DECLARE( ui_font_KR40);

// UI INIT
void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
