// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.1
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "../ui.h"

void ui_Screen1_screen_init(void)
{
ui_Screen1 = lv_obj_create(NULL);
lv_obj_clear_flag( ui_Screen1, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_Screen1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Screen1, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Image_bg = lv_img_create(ui_Screen1);
lv_img_set_src(ui_Image_bg, &ui_img_1015890679);
lv_obj_set_width( ui_Image_bg, LV_SIZE_CONTENT);  /// 450
lv_obj_set_height( ui_Image_bg, LV_SIZE_CONTENT);   /// 600
lv_obj_set_align( ui_Image_bg, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_Image_bg, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_Image_bg, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_opa(ui_Image_bg, 100, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Slider_AC = lv_slider_create(ui_Screen1);
lv_slider_set_range(ui_Slider_AC, 19,26);
lv_slider_set_value( ui_Slider_AC, 0, LV_ANIM_OFF);
if (lv_slider_get_mode(ui_Slider_AC)==LV_SLIDER_MODE_RANGE ) lv_slider_set_left_value( ui_Slider_AC, 0, LV_ANIM_OFF);
lv_obj_set_width( ui_Slider_AC, 165);
lv_obj_set_height( ui_Slider_AC, 104);
lv_obj_set_x( ui_Slider_AC, -130 );
lv_obj_set_y( ui_Slider_AC, -149 );
lv_obj_set_align( ui_Slider_AC, LV_ALIGN_CENTER );
lv_obj_set_style_radius(ui_Slider_AC, 30, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_Slider_AC, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Slider_AC, 100, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_set_style_radius(ui_Slider_AC, 0, LV_PART_INDICATOR| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_Slider_AC, lv_color_hex(0xACCAF9), LV_PART_INDICATOR | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Slider_AC, 255, LV_PART_INDICATOR| LV_STATE_DEFAULT);

lv_obj_set_style_radius(ui_Slider_AC, 5, LV_PART_KNOB| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_Slider_AC, lv_color_hex(0xFFFFFF), LV_PART_KNOB | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Slider_AC, 0, LV_PART_KNOB| LV_STATE_DEFAULT);
lv_obj_set_style_pad_left(ui_Slider_AC, -45, LV_PART_KNOB| LV_STATE_DEFAULT);
lv_obj_set_style_pad_right(ui_Slider_AC, -45, LV_PART_KNOB| LV_STATE_DEFAULT);
lv_obj_set_style_pad_top(ui_Slider_AC, -20, LV_PART_KNOB| LV_STATE_DEFAULT);
lv_obj_set_style_pad_bottom(ui_Slider_AC, -20, LV_PART_KNOB| LV_STATE_DEFAULT);

ui_Label_AC = lv_label_create(ui_Slider_AC);
lv_obj_set_width( ui_Label_AC, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label_AC, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Label_AC, -45 );
lv_obj_set_y( ui_Label_AC, 27 );
lv_obj_set_align( ui_Label_AC, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label_AC,"AC");
lv_obj_set_style_text_color(ui_Label_AC, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Label_AC, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_align(ui_Label_AC, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Label_AC, &ui_font_KR25, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Label_Temp = lv_label_create(ui_Slider_AC);
lv_obj_set_width( ui_Label_Temp, 64);
lv_obj_set_height( ui_Label_Temp, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Label_Temp, 15 );
lv_obj_set_y( ui_Label_Temp, 27 );
lv_obj_set_align( ui_Label_Temp, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label_Temp,"0°");
lv_obj_set_style_text_color(ui_Label_Temp, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Label_Temp, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_align(ui_Label_Temp, LV_TEXT_ALIGN_RIGHT, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Label_Temp, &ui_font_KR20, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Image1 = lv_img_create(ui_Slider_AC);
lv_img_set_src(ui_Image1, &ui_img_1565510499);
lv_obj_set_width( ui_Image1, LV_SIZE_CONTENT);  /// 30
lv_obj_set_height( ui_Image1, LV_SIZE_CONTENT);   /// 30
lv_obj_set_x( ui_Image1, 64 );
lv_obj_set_y( ui_Image1, 27 );
lv_obj_set_align( ui_Image1, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_Image1, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_Image1, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Label_Date = lv_label_create(ui_Screen1);
lv_obj_set_width( ui_Label_Date, 177);
lv_obj_set_height( ui_Label_Date, 30);
lv_obj_set_x( ui_Label_Date, 123 );
lv_obj_set_y( ui_Label_Date, -262 );
lv_obj_set_align( ui_Label_Date, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label_Date,"3 Fri, May");
lv_obj_set_style_text_align(ui_Label_Date, LV_TEXT_ALIGN_RIGHT, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Label_Date, &ui_font_KR25, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Label_Time = lv_label_create(ui_Screen1);
lv_obj_set_width( ui_Label_Time, 242);
lv_obj_set_height( ui_Label_Time, 48);
lv_obj_set_x( ui_Label_Time, -88 );
lv_obj_set_y( ui_Label_Time, -267 );
lv_obj_set_align( ui_Label_Time, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label_Time,"10:10 PM");
lv_obj_set_style_text_align(ui_Label_Time, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Label_Time, &ui_font_KR40, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Slider_Lamp = lv_slider_create(ui_Screen1);
lv_slider_set_value( ui_Slider_Lamp, 0, LV_ANIM_OFF);
if (lv_slider_get_mode(ui_Slider_Lamp)==LV_SLIDER_MODE_RANGE ) lv_slider_set_left_value( ui_Slider_Lamp, 0, LV_ANIM_OFF);
lv_obj_set_width( ui_Slider_Lamp, 243);
lv_obj_set_height( ui_Slider_Lamp, 107);
lv_obj_set_x( ui_Slider_Lamp, 87 );
lv_obj_set_y( ui_Slider_Lamp, -149 );
lv_obj_set_align( ui_Slider_Lamp, LV_ALIGN_CENTER );
lv_obj_set_style_radius(ui_Slider_Lamp, 30, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_Slider_Lamp, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Slider_Lamp, 100, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_set_style_radius(ui_Slider_Lamp, 0, LV_PART_INDICATOR| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_Slider_Lamp, lv_color_hex(0xB4A2E4), LV_PART_INDICATOR | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Slider_Lamp, 255, LV_PART_INDICATOR| LV_STATE_DEFAULT);

lv_obj_set_style_radius(ui_Slider_Lamp, 0, LV_PART_KNOB| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_Slider_Lamp, lv_color_hex(0xFFFFFF), LV_PART_KNOB | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Slider_Lamp, 0, LV_PART_KNOB| LV_STATE_DEFAULT);

ui_Label_Lux = lv_label_create(ui_Slider_Lamp);
lv_obj_set_width( ui_Label_Lux, 93);
lv_obj_set_height( ui_Label_Lux, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Label_Lux, -24 );
lv_obj_set_y( ui_Label_Lux, -13 );
lv_obj_set_align( ui_Label_Lux, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label_Lux,"0%");
lv_obj_set_style_text_color(ui_Label_Lux, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Label_Lux, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_align(ui_Label_Lux, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Label_Lux, &ui_font_KR20, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Label_Lamp = lv_label_create(ui_Slider_Lamp);
lv_obj_set_width( ui_Label_Lamp, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label_Lamp, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Label_Lamp, -55 );
lv_obj_set_y( ui_Label_Lamp, 25 );
lv_obj_set_align( ui_Label_Lamp, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label_Lamp,"Lamp");
lv_obj_set_style_text_color(ui_Label_Lamp, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Label_Lamp, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_align(ui_Label_Lamp, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Label_Lamp, &ui_font_KR25, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Image2 = lv_img_create(ui_Slider_Lamp);
lv_img_set_src(ui_Image2, &ui_img_1819326991);
lv_obj_set_width( ui_Image2, LV_SIZE_CONTENT);  /// 30
lv_obj_set_height( ui_Image2, LV_SIZE_CONTENT);   /// 30
lv_obj_set_x( ui_Image2, -90 );
lv_obj_set_y( ui_Image2, -13 );
lv_obj_set_align( ui_Image2, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_Image2, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_Image2, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Image_Lamp = lv_img_create(ui_Screen1);
lv_img_set_src(ui_Image_Lamp, &ui_img_images_lamp_png);
lv_obj_set_width( ui_Image_Lamp, LV_SIZE_CONTENT);  /// 155
lv_obj_set_height( ui_Image_Lamp, LV_SIZE_CONTENT);   /// 210
lv_obj_set_x( ui_Image_Lamp, 202 );
lv_obj_set_y( ui_Image_Lamp, -294 );
lv_obj_set_align( ui_Image_Lamp, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_Image_Lamp, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_Image_Lamp, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Image_Lux = lv_img_create(ui_Screen1);
lv_img_set_src(ui_Image_Lux, &ui_img_images_lux_png);
lv_obj_set_width( ui_Image_Lux, LV_SIZE_CONTENT);  /// 453
lv_obj_set_height( ui_Image_Lux, LV_SIZE_CONTENT);   /// 330
lv_obj_set_x( ui_Image_Lux, 202 );
lv_obj_set_y( ui_Image_Lux, -95 );
lv_obj_set_align( ui_Image_Lux, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_Image_Lux, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_Image_Lux, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Container_TV = lv_obj_create(ui_Screen1);
lv_obj_remove_style_all(ui_Container_TV);
lv_obj_set_width( ui_Container_TV, 457);
lv_obj_set_height( ui_Container_TV, 627);
lv_obj_set_x( ui_Container_TV, -2 );
lv_obj_set_y( ui_Container_TV, 16 );
lv_obj_set_align( ui_Container_TV, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_Container_TV, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Image_TV = lv_img_create(ui_Container_TV);
lv_img_set_src(ui_Image_TV, &ui_img_403521860);
lv_obj_set_width( ui_Image_TV, LV_SIZE_CONTENT);  /// 349
lv_obj_set_height( ui_Image_TV, LV_SIZE_CONTENT);   /// 254
lv_obj_set_x( ui_Image_TV, 2 );
lv_obj_set_y( ui_Image_TV, 16 );
lv_obj_set_align( ui_Image_TV, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_Image_TV, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_Image_TV, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Image_TV_Off = lv_img_create(ui_Container_TV);
lv_img_set_src(ui_Image_TV_Off, &ui_img_310970492);
lv_obj_set_width( ui_Image_TV_Off, LV_SIZE_CONTENT);  /// 322
lv_obj_set_height( ui_Image_TV_Off, LV_SIZE_CONTENT);   /// 237
lv_obj_set_x( ui_Image_TV_Off, 22 );
lv_obj_set_y( ui_Image_TV_Off, 2 );
lv_obj_set_align( ui_Image_TV_Off, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_Image_TV_Off, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_Image_TV_Off, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Container_AC = lv_obj_create(ui_Screen1);
lv_obj_remove_style_all(ui_Container_AC);
lv_obj_set_width( ui_Container_AC, 226);
lv_obj_set_height( ui_Container_AC, 178);
lv_obj_set_x( ui_Container_AC, -127 );
lv_obj_set_y( ui_Container_AC, -192 );
lv_obj_set_align( ui_Container_AC, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_Container_AC, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Image_AC = lv_img_create(ui_Container_AC);
lv_img_set_src(ui_Image_AC, &ui_img_images_ac_png);
lv_obj_set_width( ui_Image_AC, LV_SIZE_CONTENT);  /// 181
lv_obj_set_height( ui_Image_AC, LV_SIZE_CONTENT);   /// 84
lv_obj_set_align( ui_Image_AC, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_Image_AC, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_Image_AC, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Image_AC_On = lv_img_create(ui_Container_AC);
lv_img_set_src(ui_Image_AC_On, &ui_img_330396823);
lv_obj_set_width( ui_Image_AC_On, LV_SIZE_CONTENT);  /// 159
lv_obj_set_height( ui_Image_AC_On, LV_SIZE_CONTENT);   /// 78
lv_obj_set_x( ui_Image_AC_On, -14 );
lv_obj_set_y( ui_Image_AC_On, 41 );
lv_obj_set_align( ui_Image_AC_On, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_Image_AC_On, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_Image_AC_On, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Slider_Vacuum = lv_slider_create(ui_Screen1);
lv_slider_set_value( ui_Slider_Vacuum, 50, LV_ANIM_OFF);
if (lv_slider_get_mode(ui_Slider_Vacuum)==LV_SLIDER_MODE_RANGE ) lv_slider_set_left_value( ui_Slider_Vacuum, 0, LV_ANIM_OFF);
lv_obj_set_width( ui_Slider_Vacuum, 423);
lv_obj_set_height( ui_Slider_Vacuum, 111);
lv_obj_set_x( ui_Slider_Vacuum, 0 );
lv_obj_set_y( ui_Slider_Vacuum, 230 );
lv_obj_set_align( ui_Slider_Vacuum, LV_ALIGN_CENTER );
lv_obj_set_style_radius(ui_Slider_Vacuum, 30, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_Slider_Vacuum, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Slider_Vacuum, 100, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_set_style_radius(ui_Slider_Vacuum, 0, LV_PART_INDICATOR| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_Slider_Vacuum, lv_color_hex(0x4BBC91), LV_PART_INDICATOR | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Slider_Vacuum, 255, LV_PART_INDICATOR| LV_STATE_DEFAULT);

lv_obj_set_style_radius(ui_Slider_Vacuum, 20, LV_PART_KNOB| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_Slider_Vacuum, lv_color_hex(0xFFFFFF), LV_PART_KNOB | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Slider_Vacuum, 0, LV_PART_KNOB| LV_STATE_DEFAULT);
lv_obj_set_style_pad_left(ui_Slider_Vacuum, -45, LV_PART_KNOB| LV_STATE_DEFAULT);
lv_obj_set_style_pad_right(ui_Slider_Vacuum, -45, LV_PART_KNOB| LV_STATE_DEFAULT);
lv_obj_set_style_pad_top(ui_Slider_Vacuum, -20, LV_PART_KNOB| LV_STATE_DEFAULT);
lv_obj_set_style_pad_bottom(ui_Slider_Vacuum, -20, LV_PART_KNOB| LV_STATE_DEFAULT);

ui_Label_VC = lv_label_create(ui_Slider_Vacuum);
lv_obj_set_width( ui_Label_VC, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label_VC, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Label_VC, -117 );
lv_obj_set_y( ui_Label_VC, 16 );
lv_obj_set_align( ui_Label_VC, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label_VC,"Vacuum\nCleaner");
lv_obj_set_style_text_color(ui_Label_VC, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Label_VC, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_align(ui_Label_VC, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Label_VC, &ui_font_KR25, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Label_VCB = lv_label_create(ui_Slider_Vacuum);
lv_obj_set_width( ui_Label_VCB, 87);
lv_obj_set_height( ui_Label_VCB, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Label_VCB, -107 );
lv_obj_set_y( ui_Label_VCB, -34 );
lv_obj_set_align( ui_Label_VCB, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label_VCB,"50%");
lv_obj_set_style_text_color(ui_Label_VCB, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Label_VCB, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_align(ui_Label_VCB, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Label_VCB, &ui_font_KR20, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Image3 = lv_img_create(ui_Slider_Vacuum);
lv_img_set_src(ui_Image3, &ui_img_1844661879);
lv_obj_set_width( ui_Image3, LV_SIZE_CONTENT);  /// 30
lv_obj_set_height( ui_Image3, LV_SIZE_CONTENT);   /// 30
lv_obj_set_x( ui_Image3, -170 );
lv_obj_set_y( ui_Image3, -34 );
lv_obj_set_align( ui_Image3, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_Image3, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_Image3, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Image_Vacuum = lv_img_create(ui_Screen1);
lv_img_set_src(ui_Image_Vacuum, &ui_img_images_vacuum_cleaner_png);
lv_obj_set_width( ui_Image_Vacuum, LV_SIZE_CONTENT);  /// 218
lv_obj_set_height( ui_Image_Vacuum, LV_SIZE_CONTENT);   /// 109
lv_obj_set_x( ui_Image_Vacuum, 135 );
lv_obj_set_y( ui_Image_Vacuum, 253 );
lv_obj_set_align( ui_Image_Vacuum, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_Image_Vacuum, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_Image_Vacuum, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Image_Vacuumoff = lv_img_create(ui_Image_Vacuum);
lv_img_set_src(ui_Image_Vacuumoff, &ui_img_580765743);
lv_obj_set_width( ui_Image_Vacuumoff, LV_SIZE_CONTENT);  /// 25
lv_obj_set_height( ui_Image_Vacuumoff, LV_SIZE_CONTENT);   /// 19
lv_obj_set_x( ui_Image_Vacuumoff, -44 );
lv_obj_set_y( ui_Image_Vacuumoff, 12 );
lv_obj_set_align( ui_Image_Vacuumoff, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_Image_Vacuumoff, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_Image_Vacuumoff, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Button_AC = lv_btn_create(ui_Screen1);
lv_obj_set_width( ui_Button_AC, 148);
lv_obj_set_height( ui_Button_AC, 52);
lv_obj_set_x( ui_Button_AC, -126 );
lv_obj_set_y( ui_Button_AC, -196 );
lv_obj_set_align( ui_Button_AC, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_Button_AC, LV_OBJ_FLAG_CHECKABLE | LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_Button_AC, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_Button_AC, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_Button_AC, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Button_AC, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_Button_AC, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_CHECKED );
lv_obj_set_style_bg_opa(ui_Button_AC, 0, LV_PART_MAIN| LV_STATE_CHECKED);

ui_Button_Lamp = lv_btn_create(ui_Screen1);
lv_obj_set_width( ui_Button_Lamp, 110);
lv_obj_set_height( ui_Button_Lamp, 92);
lv_obj_set_x( ui_Button_Lamp, 185 );
lv_obj_set_y( ui_Button_Lamp, -230 );
lv_obj_set_align( ui_Button_Lamp, LV_ALIGN_CENTER );
lv_obj_add_state( ui_Button_Lamp, LV_STATE_CHECKED );     /// States
lv_obj_add_flag( ui_Button_Lamp, LV_OBJ_FLAG_CHECKABLE | LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_Button_Lamp, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_Button_Lamp, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_Button_Lamp, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Button_Lamp, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_Button_Lamp, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_CHECKED );
lv_obj_set_style_bg_opa(ui_Button_Lamp, 0, LV_PART_MAIN| LV_STATE_CHECKED);

ui_Button_TV = lv_btn_create(ui_Screen1);
lv_obj_set_width( ui_Button_TV, 278);
lv_obj_set_height( ui_Button_TV, 157);
lv_obj_set_x( ui_Button_TV, 22 );
lv_obj_set_y( ui_Button_TV, 10 );
lv_obj_set_align( ui_Button_TV, LV_ALIGN_CENTER );
lv_obj_add_state( ui_Button_TV, LV_STATE_CHECKED );     /// States
lv_obj_add_flag( ui_Button_TV, LV_OBJ_FLAG_CHECKABLE | LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_Button_TV, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_Button_TV, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_Button_TV, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Button_TV, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_Button_TV, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_CHECKED );
lv_obj_set_style_bg_opa(ui_Button_TV, 0, LV_PART_MAIN| LV_STATE_CHECKED);

ui_Button_VC = lv_btn_create(ui_Screen1);
lv_obj_set_width( ui_Button_VC, 141);
lv_obj_set_height( ui_Button_VC, 80);
lv_obj_set_x( ui_Button_VC, 137 );
lv_obj_set_y( ui_Button_VC, 253 );
lv_obj_set_align( ui_Button_VC, LV_ALIGN_CENTER );
lv_obj_add_state( ui_Button_VC, LV_STATE_CHECKED );     /// States
lv_obj_add_flag( ui_Button_VC, LV_OBJ_FLAG_CHECKABLE | LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_Button_VC, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_Button_VC, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_Button_VC, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Button_VC, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_Button_VC, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_CHECKED );
lv_obj_set_style_bg_opa(ui_Button_VC, 0, LV_PART_MAIN| LV_STATE_CHECKED);

}
